name: 'Jzero Action'
description: 'Executes commands using the Jzero tool.'

author: 'jzero-io'
branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  args:
    description: 'Arguments to pass to the Jzero command.'
    required: true
    default: ''
  version:
    description: 'Version of the Jzero image to use.'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Run Jzero
      uses: docker://jaronnie/jzero:${{ inputs.version }}
      with:
        args: ${{ inputs.args }}