name: jzero-action-test

on:
  push:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: jzero-io/jzero-action@v1
        with:
          args: version
          version: v0.23.7

      - name: cd examples
        run: cd examples

      - uses: jzero-io/jzero-action@v1
        with:
          args: gen

      - uses: jzero-io/jzero-action@v1
        with:
          args: gen sdk --goModule github.com/jzero/test --output test

      - name: list test sdk
        run: ls -l test
