name: jzero-action-test

on:
  push:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: jzero-io/jzero-action@v0.0.2
        with:
          args: version
          version: v0.22.0

      - uses: jzero-io/jzero-action@v0.0.1
        with:
          args: gen sdk --module github.com/jzero/test -d test

      - uses: jzero-io/jzero-action@v0.0.1
        with:
          args: gen zrpcclient

      - name: list test sdk and client
        run: ls -l test; ls -l zrpcclient-go
