name: jzero-action-test

on:
  push:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./
        with:
          args: version
          version: v0.22.0

      - uses: ./
        with:
          args: version
          # user latest always

      - uses: ./
        with:
          args: gen sdk --module github.com/jzero/test -d test

      - name: list test sdk
        run: ls -l test
